---
  - name: Install centos-release-openstack-ocata
    yum: name=centos-release-openstack-ocata state=present
    register: openstack_repo

  - name: Update packages
    yum: name=* state=latest
    when: openstack_repo | changed

  - name: Install OpenStack Client
    yum: name={{ item }} state=present
    with_items:
      - python-openstackclient
      - openstack-selinux
