---
  - name: Install centos-release-openstack-mitaka
    yum: name=centos-release-openstack-mitaka state=present

  - name: Update packages
    yum: name=* state=latest

  - name: Install OpenStack Client
    yum: name={{ item }} state=present
    with_items:
      - python-openstackclient
      - openstack-selinux
