---
  - name: Create nova service
    os_keystone_service:
      cloud: default
      description: "OpenStack Compute"
      name: "nova"
      service_type: "compute"

  - name: Create nova endpoints
    delegate_to: "{{ keystone_fqdn }}"
    keystone:
      login_user: admin
      login_password: "{{ keystone_admin_password }}"
      login_project_name: "admin"
      command: "ensure_endpoint"
      region_name: "RegionOne"
      service_name: "nova"
      service_type: "compute"
      endpoint_list:
        - url: "http://{{ nova_fqdn }}:8774/v2.1/%(tenant_id)s"
          interface: "public"
        - url: "http://{{ nova_fqdn }}:8774/v2.1/%(tenant_id)s"
          interface: "internal"
        - url: "http://{{ nova_fqdn }}:8774/v2.1/%(tenant_id)s"
          interface: "admin"
      endpoint: "http://{{ keystone_fqdn }}:35357/v3"
      insecure: yes

  - name: Create nova user
    os_user:
      cloud: default
      name: nova
      default_project: service
      password: "{{ nova_password }}"
      email: nova@example.com
      domain: Default

  - name: Add nova user to admin role
    os_user_role:
      cloud: default
      user: nova
      project: service
      role: admin
