---
  - name: Include OS specific variables
    include_vars: "{{ ansible_os_family }}.yml"

  - include: install.yml

  - include: dbsetup.yml
    when: not is_compute

  - include: access.yml
    when: not is_compute

  - include: startservices.yml
