---
  - name: restart neutron controller
    service: name={{ item }} enabled=yes state=restarted
    with_items:
      - neutron-server
      - neutron-linuxbridge-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent
      - neutron-l3-agent
    when: not is_compute

  - name: restart neutron compute
    service: name=neutron-linuxbridge-agent enabled=yes state=restarted
    when: is_compute
