---
  - name: Create mysql heat database
    delegate_to: "{{ mysql_server }}"
    mysql_db:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: heat
      state: present
      encoding: utf8

  - name: Create mysql heat user
    delegate_to: "{{ mysql_server }}"
    mysql_user:
      name: heat
      password: "{{ heat_database_password }}"
      priv: heat.*:ALL
      state: present
      host: "{{ item }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
    with_items:
       - "%"
       - "localhost"

  - name: Perform a heat DB sync
    command: "heat-manage db_sync"
    become: yes
    become_user: heat
    register: result
    changed_when: "'migrate.versioning.api' in result.stderr and result.rc == 0"
