---
  - name: restart nova controller
    service: name={{ item }} enabled=yes state=restarted
    with_items: "{{ nova_controller_services }}"
    when: not is_compute

  - name: restart nova compute
    service: name={{ item }} enabled=yes state=restarted
    with_items: "{{ nova_compute_services }}"
    when: is_compute
