---
  - name: Create service project
    os_project:
      cloud: default
      name: service
      description: Service Project

  - name: Create custom projects
    os_project:
      cloud: default
      name: "{{ item.name }}"
      domain_id: "{{ item.domain_id | default('default') }}"
      description: "{{ item.description | default('') }}"
    with_items: "{{ keystone_projects | default([]) }}"

  - name: Create user role
    os_keystone_role:
      cloud: default
      name: user

  - name: Create custom roles
    os_keystone_role:
      cloud: default
      name: "{{ item }}"
    with_items: "{{ keystone_roles | default([]) }}"

  - name: Create custom users
    os_user:
      cloud: default
      name: "{{ item.name }}"
      default_project: "{{ item.project }}"
      password: "{{ item.password }}"
      email: "{{ item.email | default('') }}"
      domain: "{{ item.domain | default('Default') }}"
    with_items: "{{ keystone_users | default([]) }}"

  - name: Map users and roles
    os_user_role:
      cloud: default
      user: "{{ item.user }}"
      project: "{{ item.project }}"
      role: "{{ item.role }}"
    with_items: "{{ keystone_user_roles | default([]) }}"
