---
  - name: Create mysql keystone database
    mysql_db:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: keystone
      state: present
      encoding: utf8

  - name: Create mysql keystone user
    mysql_user:
      name: keystone
      password: "{{ keystone_database_password }}"
      priv: keystone.*:ALL
      state: present
      host: "{{ item }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
    with_items:
       - "%"
       - "localhost"

  - name: Perform a keystone DB sync
    command: "keystone-manage db_sync"
    become: yes
    become_user: keystone
    register: result
    changed_when: result.stderr != "" and result.rc == 0
