---
  - name: Prevent keystone from starting at install time
    template: dest=/etc/init/keystone.override src=keystone.override.j2

  - name: Install keystone packages
    apt: name={{ item }} state=present
    with_items:
      - memcached
      - keystone
      - apache2
      - libapache2-mod-wsgi

  - name: Configure keystone
    template: dest=/etc/keystone/keystone.conf src=keystone.conf.j2
    notify: restart apache2

  # TODO: Configure apache server name

  - name: Create keystone virtual host in apache
    template:
      dest: /etc/apache2/sites-available/wsgi-keystone.conf
      src: wsgi-keystone.conf.j2
    notify: restart apache2

  - name: Enable keystone virtual host
    file:
      src: /etc/apache2/sites-available/wsgi-keystone.conf
      dest: /etc/apache2/sites-enabled/wsgi-keystone.conf
      state: link
    notify: restart apache2
