---
  - name: Prevent keystone from starting at install time (trusty)
    template: dest=/etc/init/keystone.override src=keystone.override.j2
    when: ansible_distribution_release == "trusty"

  - name: Install keystone packages
    package: name={{ item }} state=present
    with_items: "{{ keystone_packages }}"

  - name: Stop keystone services (xenial)
    service: name=keystone enabled=no state=stopped

  - name: Configure keystone
    template: dest=/etc/keystone/keystone.conf src=keystone.conf.j2
    notify: restart {{ webserver }}

  # TODO: Configure apache server name

  - name: Create keystone virtual host in {{ webserver }}
    template:
      dest: "{{ webserver_conf_dir }}/wsgi-keystone.conf"
      src: wsgi-keystone.conf.j2
    notify: restart {{ webserver }}

  - name: Enable keystone virtual host
    file:
      src: /etc/apache2/sites-available/wsgi-keystone.conf
      dest: /etc/apache2/sites-enabled/wsgi-keystone.conf
      state: link
    notify: restart apache2
    when: ansible_os_family == "Debian"
