---
  - name: Install keystone packages
    package: name={{ item }} state=present
    with_items: "{{ keystone_packages }}"
    notify: restart {{ webserver }}

  - name: Configure keystone
    template: dest=/etc/keystone/keystone.conf src=keystone.conf.j2
    notify: restart {{ webserver }}

  # TODO: Configure apache server name
