---
  - name: Include OS specific variables
    include_vars: "{{ ansible_os_family }}.yml"

  - include: install.yml
  - include: dbsetup.yml
  - include: startservices.yml
  - include: bootstrap.yml

  - name: Create openrc file
    become: no
    local_action: template src=openrc.j2 dest=~/openrc mode=0600

  - name: Create ~/.config/openstack directory
    file: path={{ item }} state=directory
    with_items:
      - ~/.config
      - ~/.config/openstack

  - name: Create clouds.yaml file
    template: src=clouds.yaml.j2 dest=~/.config/openstack/clouds.yaml mode=0600

  - include: access.yml

  # TODO: Disable admin_token
