---
  - name: Create cinder services
    os_keystone_service:
      cloud: default
      description: "OpenStack Block Storage"
      name: "{{ item.name }}"
      service_type: "{{ item.type }}"
    with_items:
      - name: cinder
        type: volume
      - name: cinderv2
        type: volumev2

  - name: Create cinder endpoints
    delegate_to: "{{ keystone_fqdn }}"
    keystone:
      login_user: admin
      login_password: "{{ keystone_admin_password }}"
      login_project_name: "admin"
      command: "ensure_endpoint"
      region_name: "RegionOne"
      service_name: "{{ item.name }}"
      service_type: "{{ item.type }}"
      endpoint_list:
        - url: "{{ item.url }}"
          interface: "public"
        - url: "{{ item.url }}"
          interface: "internal"
        - url: "http://{{ cinder_fqdn }}:8776/v1/%(tenant_id)s"
          interface: "admin"
      endpoint: "http://{{ keystone_fqdn }}:35357/v3"
      insecure: yes
    with_items:
      - name: cinder
        type: volume
        url: "http://{{ cinder_fqdn }}:8776/v1/%(tenant_id)s"
      - name: cinderv2
        type: volumev2
        url: "http://{{ cinder_fqdn }}:8776/v2/%(tenant_id)s"

  - name: Create cinder user
    os_user:
      cloud: default
      name: cinder
      default_project: service
      password: "{{ cinder_password }}"
      email: cinder@example.com
      domain: Default

  - name: Add cinder user to admin role
    os_user_role:
      cloud: default
      user: cinder
      project: service
      role: admin
