---
  - name: Install horizon packages
    package: name=openstack-dashboard state=present
    notify: restart {{ webserver }}

  - name: Configure horizon
    template:
      src: 10_custom_settings.py.j2
      dest: /usr/share/openstack-dashboard/openstack_dashboard/local/local_settings.d/10_custom_settings.py
    notify: restart {{ webserver }}
