---
  - name: Create glance service
    keystone:
      login_user: admin
      login_password: "{{ keystone_admin_password }}"
      login_project_name: "admin"
      command: "ensure_service"
      service_name: "glance"
      service_type: "image"
      description: "OpenStack Image"
      endpoint: "http://{{ keystone_fqdn }}:35357/v3"
      insecure: yes

  - name: Create glance endpoints
    keystone:
      login_user: admin
      login_password: "{{ keystone_admin_password }}"
      login_project_name: "admin"
      command: "ensure_endpoint"
      region_name: "RegionOne"
      service_name: "glance"
      service_type: "image"
      endpoint_list:
        - url: "http://{{ glance_fqdn }}:9292"
          interface: "public"
        - url: "http://{{ glance_fqdn }}:9292"
          interface: "internal"
        - url: "http://{{ glance_fqdn }}:9292"
          interface: "admin"
      endpoint: "http://{{ keystone_fqdn }}:35357/v3"
      insecure: yes

  - name: Create glance user
    os_user:
      cloud: default
      name: glance
      default_project: service
      password: "{{ glance_password }}"
      email: glance@example.com
      domain: Default

  - name: Add glance user to admin role
    os_user_role:
      cloud: default
      user: glance
      project: service
      role: admin
