---
  - name: Create mysql glance database
    delegate_to: "{{ mysql_server }}"
    mysql_db:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: glance
      state: present
      encoding: utf8

  - name: Create mysql glance user
    delegate_to: "{{ mysql_server }}"
    mysql_user:
      name: glance
      password: "{{ glance_database_password }}"
      priv: glance.*:ALL
      state: present
      host: "{{ item }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
    with_items:
       - "%"
       - "localhost"

  - name: Perform a glance DB sync
    command: "glance-manage db_sync"
    become: yes
    become_user: glance
    register: result
    changed_when: "'migrate.versioning.api' in result.stderr and result.rc == 0"
