---
  - name: Install glance packages
    package: name={{ item }} state=present
    with_items: "{{ glance_packages }}"

  - name: Configure glance
    template: dest=/etc/glance/{{ item }} src={{ item }}.j2
    with_items:
      - glance-api.conf
      - glance-registry.conf
    notify: restart glance
