---
  - name: Create neutron service
    keystone:
      login_user: admin
      login_password: "{{ keystone_admin_password }}"
      login_project_name: admin
      command: ensure_service
      service_name: neutron
      service_type: network
      description: OpenStack Networking
      endpoint: "http://{{ keystone_fqdn }}:35357/v3"
      insecure: yes

  - name: Create neutron endpoints
    keystone:
      login_user: admin
      login_password: "{{ keystone_admin_password }}"
      login_project_name: admin
      command: ensure_endpoint
      region_name: RegionOne
      service_name: neutron
      service_type: network
      endpoint_list:
        - url: "http://{{ neutron_fqdn }}:9696"
          interface: public
        - url: "http://{{ neutron_fqdn }}:9696"
          interface: internal
        - url: "http://{{ neutron_fqdn }}:9696"
          interface: admin
      endpoint: "http://{{ keystone_fqdn }}:35357/v3"
      insecure: yes

  - name: Create neutron user
    os_user:
      cloud: default
      name: neutron
      default_project: service
      password: "{{ neutron_password }}"
      email: neutron@example.com
      domain: Default

  - name: Add neutron user to admin role
    os_user_role:
      cloud: default
      user: neutron
      project: service
      role: admin
