---
  - name: Install neutron packages (controller)
    package: name={{ item }} state=present
    with_items: "{{ neutron_controller_packages }}"
    when: not is_compute

  - name: Install neutron packages (compute)
    package: name={{ item }} state=present
    with_items: "{{ neutron_compute_packages }}"
    when: is_compute

  - name: Configure neutron (controller)
    template: dest=/etc/neutron/{{ item }} src={{ item }}.j2
    with_items:
      - neutron.conf
      - plugins/ml2/ml2_conf.ini
      - plugins/ml2/linuxbridge_agent.ini
      - l3_agent.ini
      - dhcp_agent.ini
      - metadata_agent.ini
    notify:
      - restart neutron controller
    when: not is_compute

  - name: Configure neutron (compute)
    template: dest=/etc/neutron/{{ item }} src={{ item }}.j2
    with_items:
      - neutron.conf
      - plugins/ml2/linuxbridge_agent.ini
    notify:
      - restart neutron compute
    when: is_compute

  - name: Create link to ml2_conf.ini
    file:
      path: /etc/neutron/plugin.ini
      src: /etc/neutron/plugins/ml2/ml2_conf.ini
      state: link
    when: ansible_os_family == "RedHat"
