---
  - meta: flush_handlers

  - name: Start neutron services (controller)
    service: name={{ item }} state=started
    with_items:
      - neutron-server
      - neutron-linuxbridge-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent
      - neutron-l3-agent
    when: not is_compute

  - name: Start neutron services (compute)
    service: name=neutron-linuxbridge-agent state=started
    when: is_compute
